# -*- coding: utf-8 -*-
"""Ball Image Recognition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1bCRXuVSyaidh3iIl2d96i6BdmQal3W

#### Import the libraries
"""

import keras
from keras import backend as K
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.models import Model
from keras.applications import imagenet_utils
import numpy as np
from IPython.display import Image

"""#### Import MobileNet - the image recognition model"""

mobile = keras.applications.mobilenet.MobileNet()

"""#### Function to Prepare Images"""

def prepare_image(file):
    img_path = ''
    img = image.load_img(img_path + file, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array_expanded_dims = np.expand_dims(img_array, axis=0)
    return keras.applications.mobilenet.preprocess_input(img_array_expanded_dims)

"""#### Preview Image"""

Image(filename='basketball ball 1.jpg')

"""#### Image Prediction"""

preprocessed_image = prepare_image('basketball ball 1.jpg')
predictions = mobile.predict(preprocessed_image)
results = imagenet_utils.decode_predictions(predictions)
results